export const GET_PROFILES='GET_PROFILES';
export const ADD_PROFILE='ADD_PROFILE';
export const DELETE_PROFILE='DELETE_PROFILE';
export const UPDATE_PROFILE='UPDATE_PROFILE';
export const SEARCH_PROFILE='SEARCH_PROFILE';
export const GET_PROFILE='GET_PROFILE';



